### ISSUE TITLE
Performance compared to other common models?

### ISSUE THREAD

**Issue by tronving** [kernelmachine/cbtm#1]
Considering using this to train some self instructors. Do the pretrained models score well on benchmarks?

**Comment by kernelmachine** [comment]
We have few shot text classification results in the paper. We haven’t evaluated the models on other benchmarks yet, but we have released the models (check bottom of README), and they can be converted to HF format for further evaluation. So far, our perplexity results have been tracking well with downstream performance, so I would expect our cBTM models to outperform equivalent dense models on other benchmarks too. 

Keep in mind that our models have been specifically trained on C4 and S2ORC, so they might under perform on certain tasks.
